.PHONY: clean All

All:
	@echo "----------Building project:[ FIRSTWORKSPACE - Debug ]----------"
	@cd "FIRSTWORKSPACE" && "$(MAKE)" -f  "FIRSTWORKSPACE.mk"
clean:
	@echo "----------Cleaning project:[ FIRSTWORKSPACE - Debug ]----------"
	@cd "FIRSTWORKSPACE" && "$(MAKE)" -f  "FIRSTWORKSPACE.mk" clean
