.PHONY: clean All

All:
	@echo "----------Building project:[ Compiler_warning - Debug ]----------"
	@cd "Compiler_warning" && "$(MAKE)" -f  "Compiler_warning.mk"
clean:
	@echo "----------Cleaning project:[ Compiler_warning - Debug ]----------"
	@cd "Compiler_warning" && "$(MAKE)" -f  "Compiler_warning.mk" clean
