.PHONY: clean All

All:
	@echo "----------Building project:[ linker_errors - Debug ]----------"
	@cd "linker_errors" && "$(MAKE)" -f  "linker_errors.mk"
clean:
	@echo "----------Cleaning project:[ linker_errors - Debug ]----------"
	@cd "linker_errors" && "$(MAKE)" -f  "linker_errors.mk" clean
