.PHONY: clean All

All:
	@echo "----------Building project:[ first_Program - Debug ]----------"
	@cd "first_Program" && "$(MAKE)" -f  "first_Program.mk"
clean:
	@echo "----------Cleaning project:[ first_Program - Debug ]----------"
	@cd "first_Program" && "$(MAKE)" -f  "first_Program.mk" clean
